### ISSUE TITLE
style grouping headers

### ISSUE THREAD

**Issue by bchr02** [OlegKi/jqGrid#6]
has your proposed solution been implemented?
http://stackoverflow.com/questions/19841588/jqgrid-change-background-color-of-grouping-header

**Comment by b2dac** [comment]
actually that solution might not be exactly what I am looking for. I am only looking to set the default background color for the first three groups regardless of what the value is. Something like this: 
```javascript
			loadComplete: function () {
				var i,
					headerIdPrefix = this.id + "ghead_",
					groups = $(this).jqGrid("getGridParam", "groupingView").groups;
					
				$("#" + headerIdPrefix + groups[0].idx + "_" + 0).addClass(class1);
				$("#" + headerIdPrefix + groups[1].idx + "_" + 1).addClass(class2);
				$("#" + headerIdPrefix + groups[2].idx + "_" + 2).addClass(class3);
			}
```

**Comment by b2dac** [comment]
Actually, I am only looking to format by group.idx. So something like this works for me. Is there something in the API that allows one to do this with less code?
````javascript
loadComplete: function () {
				var i, 
					group,
					cssClass,
					headerIdPrefix = this.id + "ghead_",
					groups = $(this).jqGrid("getGridParam", "groupingView").groups,
					l = groups.length;
				
				for (i = 0; i < l; i++) {
					group = groups[i];
					
					switch (group.idx) {
							case 0:
								cssClass = "class1";
								break;
							case 1:
								cssClass = "class2";
								break;
							case 2:
								cssClass = "class3";
								break;
							default:
								cssClass = "";
								break;
							}
					
					if (cssClass !== "") {
								$("#" + headerIdPrefix + group.idx + "_" + i).addClass(cssClass);
							}
				}
			}
````

**Comment by OlegKi** [comment]
The current implementation of jqGrid don't provide you to set attributes on grouping column, but you can use `groupingView.formatDisplayField` to archive almost the same results.

I created [the demo](http://www.ok-soft-gmbh.com/jqGrid/OK/b2dac.htm) which displays 
![b2dac](https://cloud.githubusercontent.com/assets/249117/5940977/72860a8e-a70e-11e4-914c-bf8f17d8d89d.png)

Probably you can ask such common questions on the stackoverflow. In the way more people will fine the corresponding solutions.

**Comment by b2dac** [comment]
okay will do. Thank you.
